### ISSUE TITLE
Missing Data:

### ISSUE THREAD

**Issue by stuagano** [opendata/Open-Data-Census#101]
STATE: Michigan
DATASET: Checkbook 
URL: http://spending.michigan.gov/#!/year/2015/

DESCRIPTION/COMMENTS: This is a subset of a new transparency site for them at http://transparency.michigan.gov/ which includes more data then what is tracked soley in the checkbook

**Comment by waldoj** [comment]
Great! Thanks for this, @stuagano. That brought this dataset's grade up from a C to a B.
