### ISSUE TITLE
Missing Data: Delaware Addresses

### ISSUE THREAD

**Issue by ajturner** [opendata/Open-Data-Census#102]
STATE: Delaware
DATASET: Addresses
URL: http://opendata.arcgis.com/datasets/2fa1238f0ad84bb7961233d9c39fa2c5_0

DESCRIPTION/COMMENTS:

[Here you might describe the quality of the data, rate it using the census' metrics, suggest changes to an existing dataset, etc.]

**Comment by waldoj** [comment]
An 80% rating is a big step up from 0%. :) Thanks so much for this update, Andrew!
