### ISSUE TITLE
Missing Data: Maryland checkbook bulk data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#103]
STATE: MD
DATASET: Checkbook
URL: https://data.maryland.gov/Budget/State-of-Maryland-Payments-Data-FY2008-to-FY2015/gja3-vy5r

This bulk dataset shows all payments made by state agencies from Fiscal Years 2008 to 2015 which were $25,000 or more. All parties receiving funds are shown: private businesses, local governments, non-profit organizations, and individuals.

**Comment by waldoj** [comment]
That brings Maryland up to an A− for this dataset, a big improvement. Thanks!
