### ISSUE TITLE
Missing Data: Oklahoma checkbook bulk data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#104]
STATE: OK
DATASET: Checkbook
URL: https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2016

Current and past years are available for download as CSVs and accessible via API.

https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2016
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2015
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2014
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2013
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2012
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2011
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2010
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2009
https://data.ok.gov/dataset/state-oklahoma-vendor-payments-fiscal-year-2008

Summary expenditure data is also available:

https://data.ok.gov/dataset/expenditure-summary-fiscal-year-2015

**Comment by waldoj** [comment]
The grade for this went from 50% to 100%—a huge improvement!
