### ISSUE TITLE
Missing Data: North Carolina checkbook CSV data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#105]
STATE: NC
DATASET: Checkbook
URL: http://www.ncopenbook.gov/ContractsHome.jsp

Various CSV files of payments by agencies or by payee are available here: http://www.ncopenbook.gov/ContractsHome.jsp

**Comment by waldoj** [comment]
Bulk data bumped their score a bit. It's been abandoned for a few years, but at least the old data is available as actual data, instead of HTML. Thanks!
