### ISSUE TITLE
Missing Data: Wyoming checkbook

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#106]
STATE: WY
DATASET: Checkbook
URL: http://sao.wyo.gov/vendor-payments

Not exactly open data, but the state does maintain a checkbook site here: http://sao.wyo.gov/vendor-payments

**Comment by waldoj** [comment]
This brought them up from 0% to 35%. F ain't a great score, but it's a far sight better than 0%. Thanks!
