### ISSUE TITLE
Missing Data: DC Checkbook bulk data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#107]
STATE: DC
DATASET: Checkbook
URL: http://opendata.dc.gov/datasets/f61f962c2ce84f2caa1919d425c8061d_0

2015: http://opendata.dc.gov/datasets/f61f962c2ce84f2caa1919d425c8061d_0
2014: http://opendata.dc.gov/datasets/b9e53d4185ae490cb41bc895be829a7e_0
2013: http://opendata.dc.gov/datasets/abc00ed761234b8387ddaeb4e759fc70_0
2012: http://opendata.dc.gov/datasets/9057e899b64543f79e16bae0e1950e07_0

**Comment by waldoj** [comment]
Bringing this dataset up from 0% to 85%, this brings Washington D.C. up from a grade of a D+ to a C+, a mighty big improvement. Thanks so much for adding this!
