### ISSUE TITLE
Missing Data: Oklahoma legislation

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#108]
STATE: OK
DATASET: legislation
URL: http://www.oklegislature.gov/TextOfMeasures.aspx

This does offer bulk Excel downloads of legislative data. The interface is quite primitive.

http://www.oklegislature.gov/TextOfMeasures.aspx

**Comment by waldoj** [comment]
That's a huge improvement—it brought their score up enormously. Thank you!
