### ISSUE TITLE
Virginia: Restaurant Inspections url changed

### ISSUE THREAD

**Issue by harper** [opendata/Open-Data-Census#111]
STATE: Virginia
DATASET: Restaurant Inspections
URL: http://healthspace.com/Clients/VDH/VDH/web.nsf/home.xsp

DESCRIPTION/COMMENTS:

Url changed to http://healthspace.com/Clients/VDH/VDH/web.nsf/home.xsp

Old page at http://www.healthspace.com/Clients/VDH/VDH_Website.nsf shows updated url but no 301 redirect

**Comment by waldoj** [comment]
Thanks so much, @harper! I've got that corrected now.
