### ISSUE TITLE
CT Incarceration Data

### ISSUE THREAD

**Issue by OpenDataCT** [opendata/Open-Data-Census#113]
State: CT
Dataset: Incarceration
url: https://data.ct.gov/Public-Safety/Department-of-Corrections-Quarterly-Average-Facilt/f8ar-pgu4

Our Department of Corrections has published an additional dataset that details the quartely average population and capacity of CT Correctional Facilities. This is in addition to the previously inventoried data which details the daily population count of these facilties. This data is being published as open data to satisfy a legislative reporting requirement, but also seems to meet all of the criteria for the Incarceration data in the Census.

**Comment by waldoj** [comment]
Thanks for this, Tyler! I've updated that record accordingly, bringing it from a 95% to a 100% score. Of course, having the data spread across _two_ datasets isn't ideal, but that's not something that we grade against, so ¯\\\_(ツ)\_/¯. This didn't affect the state’s overall score enough to nudge it up from a score of 84.
