### ISSUE TITLE
Please review our new Open Checkbook application

### ISSUE THREAD

**Issue by rhondalehman** [opendata/Open-Data-Census#117]
STATE: Delaware
DATASET:   State of Delaware Checkbook
URL:   checkbook.delaware.gov   and the raw dataset is at:  https://data.delaware.gov/Government-and-Finance/State-of-Delaware-Checkbook/5s6n-7hpx 

DESCRIPTION/COMMENTS:

The State of Delaware Checkbook, as well as Revenue, and State Employee Credit Cards Transactions are updated monthly and available in a machine-readable format on the new Delaware Open Data Portal.  In addition, a new Open Checkbook application has been added that provides many ways to slice and dice the checkbook data.

**Comment by waldoj** [comment]
Reviewed and added. Thank you, Rhonda!
