### ISSUE TITLE
Please review Restaurant Inspections data on our new Open Data Portal

### ISSUE THREAD

**Issue by rhondalehman** [opendata/Open-Data-Census#118]
STATE: Delaware
DATASET: Restaurant Inspection Violations
URL:  https://data.delaware.gov/Health/Restaurant-Inspection-Violations/384s-wygj

DESCRIPTION/COMMENTS:

Please review our new Restaurant Inspection Violations dataset that is updated monthly on our new Open Data Portal.

**Comment by waldoj** [comment]
Done—thank you!
