### ISSUE TITLE
Missing Data:WA Address points

### ISSUE THREAD

**Issue by will-saunders** [opendata/Open-Data-Census#122]
STATE: WA
DATASET: Address Points
URL: https://state-wamas.wa.gov/resources/home/

DESCRIPTION/COMMENTS:

Address point data exists, and is available to agencies and local governments for free via a RESTful API; batch file uploads and an Excel plugin are available as well.  Washington law discourages publication of a list of addresses at all, and applies a no-commercial-use restriction, so the data is (at present) available only to state and local governments.  Work on a publishable master address file is in progress.

**Comment by waldoj** [comment]
This is great news—I'm glad to hear that Washington has centralized address data (and look forward to the day when that can be public). I've updated the record accordingly.
