### ISSUE TITLE
Missing Data: WA Restaurant inspections

### ISSUE THREAD

**Issue by will-saunders** [opendata/Open-Data-Census#123]
STATE: WA
DATASET: Restaurant Inspections
URL: https://data.wa.gov/Health/Restaurant-Inspections/7ktr-3bhb

DESCRIPTION/COMMENTS:

State open data repository includes links to major county health inspection listings, summarized by WA department of Health.  Not all counties in the state report online.Most counties that do report online offer bulk download. All are offered for free without restrictive license.

**Comment by waldoj** [comment]
These new datasets are big improvements for Washington, Will—this must have been no small amount of work! I've updated this record. Thank you!
