### ISSUE TITLE
Display a spinner while loading grid data

### ISSUE THREAD

**Issue by waldoj** [opendata/Open-Data-Census#22]
It takes enough time for the grid data to be loaded from Google Sheets for somebody to wonder "is this it?" Display a spinner while awaiting that data loads.

**Comment by waldoj** [comment]
Tabletop.js doesn't appear to have any kind of baked-in support for this, but surely there's a jQuery way to do this.

**Comment by waldoj** [comment]
OK, I think this is pretty straightforward. See [this example](https://github.com/twitter/typeahead.js/issues/166#issuecomment-24890467).

**Comment by waldoj** [comment]
Basically, we display a GIF in the table, and just hide that GIF when `Tabletop.init()` finishes.

**Comment by stvnrlly** [comment]
There's also a library available for this, if you want to go that route: https://fgnass.github.io/spin.js/

**Comment by waldoj** [comment]
Oh, that seems civilized. Thanks!
