### ISSUE TITLE
Give some indication that something is happening while data is loaded

### ISSUE THREAD

**Issue by iandees** [opendata/Open-Data-Census#35]
When I first arrived on the site there was no actual census information so I looked around trying to find a link to the report but couldn't find anything. I was just about to hit back when the content actually loaded in.

I imagine this would be solved with #31, but in the mean time it might be helpful to have a loading indication of some sort while the data is pulled down from Google Sheets.

**Comment by waldoj** [comment]
I'm going to close this as a duplicate of #22, and regard it as a vote in favor of me doing something about that quickly. :)

**Comment by iandees** [comment]
:+1:
