### ISSUE TITLE
Site does not disclose what it is considering the "state repository" for each state

### ISSUE THREAD

**Issue by shua123** [opendata/Open-Data-Census#39]
One of the grading criteria's is "In the State Repository" but no where does it say what that state repository is.

**Comment by waldoj** [comment]
Yup, there's presently no place to list that. We'll probably start including that in the comments. The goal of that criterion isn't to promote the repository, so that's not a priority.

**Comment by shua123** [comment]
For transparency, and clarity, it is important to fully document the criteria you are using. If you are checking a "state repository" you need to disclose what you are checking.
