### ISSUE TITLE
"Data Exists" rating is vague

### ISSUE THREAD

**Issue by shua123** [opendata/Open-Data-Census#40]
"Data Exists
Does this data exist at all?"

Is this asking if the data exists or the data exists online? What is the methodology to determine if the data exists?

**Comment by waldoj** [comment]
If the data exists at all, [per the methodology](https://census.usopendata.org/methodology.html]. If it is not readily obvious that the data does exist, then it's necessary to consult with relevant experts in those states to determine whether the data has the data in any format, as sometimes it simply does not.

**Comment by shua123** [comment]
The methodology for Data Exists on this page is literally just the sentence "Does this data exist at all?" That is a question, not a methodology.

**Comment by waldoj** [comment]
Pull requests are welcome!
