### ISSUE TITLE
Ensure that all existing datasets have a URL

### ISSUE THREAD

**Issue by shua123** [opendata/Open-Data-Census#41]
For example, "Illinois Legislation" it says it is available online but there is no link to the site that is reviewed.

**Comment by waldoj** [comment]
The site's data is stored in Google Sheets—there are literally no requirements at _all._ It's unstructured data. I've just added a link to the home page of their legislative site, since that's better than nothing!

**Comment by shua123** [comment]
That is a start. This is just part of the ongoing issue of context and documentation missing from yes/no color coding. 
The graphics and data export sides of it were lacking but the old SunshineReview.org website evaluation wiki format (now living under ballotpedia) was nice because it allowed documentation and context around all evaluations/ratings.
http://ballotpedia.org/wiki/index.php/Evaluation_of_Illinois_state_website
http://ballotpedia.org/Evaluation_of_Illinois_county_websites

**Comment by waldoj** [comment]
Added the AZ, PA, and MI legislatures' URLs, which were the only datasets lacking URLs.
