### ISSUE TITLE
Missing Data: Minnesota Incarceration

### ISSUE THREAD

**Issue by gboone** [opendata/Open-Data-Census#52]
STATE: MN
DATASET: Incarceration
URL: https://www.doc.state.mn.us/pages/index.php/about/statistics/

DESCRIPTION:

Register of all companies that exist in the state.

Exists: yes
Digitized: yes
Public: yes
Without cost: yes
Online: yes
Machine-readable: no
Available in bulk: yes
No license restrictions: yes
Up-to-date: yes
In the state repository: no
Verifiable: no
Complete: yes

Comments:
* Each facility is available as a PDF download and the MN DOC, they are machine readable to the extent PDFs are parseable. :grimacing: The individual reports are updated daily. It's unclear if historical data is available at this level.
* A bulk download of systemwide data is available but again is a PDF and filenames are unpredictable and would likely require scraping the webpage.
* The site _is_ available over HTTPS but it is not enabled by default.

**Comment by waldoj** [comment]
Thank you, Greg! Interesting about the site being available by HTTPS, but not by default. I'm going to have to chew over how whether they should get a `yes` or a `no` on that metric.

I'm sorry that it wasn't possible file a pull request to add this directly, but [we'll get there](https://github.com/opendata/Open-Data-Census/issues/31). :)

**Comment by gboone** [comment]
No problem, just updated the URL, too. Working on real estate now!

**Comment by waldoj** [comment]
[I've got this up on the census now](https://census.usopendata.org/datasets.html?state=Minnesota)—thank you!
