### ISSUE TITLE
Missing Data: Minnesota Real Estate

### ISSUE THREAD

**Issue by gboone** [opendata/Open-Data-Census#53]
STATE: MN
DATASET: Real Estate
URL: https://www.mn.gov/admin/government/real-estate/

State-owned land and buildings.

Exists: yes
Digitized: no
Public: no
Without cost: maybe
Online: no
Machine-readable: no
Available in bulk: no
No license restrictions: maybe
Up-to-date: maybe
In the state repository: no
Verifiable: no
Complete: no

Comments:
Excerpt from the webpage:

>  The State owns a total of 29 million square feet in more than 5,000 buildings. This real estate is managed by 20 custodial agencies, ranging from the Minnesota State Retirement System with one building containing 146,500 square feet, to the Department of Corrections with 283 buildings with more than 5,592,818 square feet and the Department of Human Services with 192 buildings with more than 3,000,000 square feet. Additionally, Admin leases over 3.5 million square feet of space for state agencies with annual rent totaling more than $60 million.

Seems like the data exist but are only available to agencies and their vendors buying and selling real property. There's no information on whether the state would charge a member of the public or put restrictions on how they might use it.

**Comment by waldoj** [comment]
[I've got this up on the census now](https://census.usopendata.org/datasets.html?state=Minnesota)—thank you!
