### ISSUE TITLE
Missing Data: Minnesota Checkbook

### ISSUE THREAD

**Issue by gboone** [opendata/Open-Data-Census#54]
STATE: MN
DATASET: Checkbook
URL: http://warehouse.swift.state.mn.us/analytics/saw.dll?dashboard

Transaction-level, per-agency spending records.

Exists: yes
Digitized: yes
Public: yes
Without cost: yes
Online: yes
Machine-readable: yes
Available in bulk: no
No license restrictions: yes
Up-to-date: maybe
In the state repository: no
Verifiable: no
Complete: no

Comments:
* You might expect to find this one the State's Budget pages; you'd be wrong. This is why we have the open data census.
* Date and check number is not available, hard to know if it's up to date

**Comment by waldoj** [comment]
[I've got this up on the census now](https://census.usopendata.org/datasets.html?state=Minnesota)—thank you!
