### ISSUE TITLE
Missing Data: Minnesota Address Points

### ISSUE THREAD

**Issue by gboone** [opendata/Open-Data-Census#55]
STATE: MN
DATASET: Address points
URL: https://gisdata.mn.gov/dataset/us-mn-co-dakota-loc-propertyinfo-addresses

Exists: yes
Digitized: yes
Public: yes
Without cost: yes
Online: yes
Machine-readable: yes
Available in bulk: yes
No license restrictions: yes
Up-to-date: yes
In the state repository: no
Verifiable: yes
Complete: no

Comments: 
* Only available for Dakota County. Maybe the rest of the state can be pieced together from other county reports? I marked "exists" yes because at least some data is available from the state's official website.
* Last update is from September 15, 2015

**Comment by waldoj** [comment]
[I've got this up on the census now](https://census.usopendata.org/datasets.html?state=Minnesota)—thank you!
