### ISSUE TITLE
Missing Data: Minnesota Restaurant Inspection

### ISSUE THREAD

**Issue by gboone** [opendata/Open-Data-Census#57]
STATE: MN
DATASET: Restaurant Inspection
URL: http://www.health.state.mn.us/macros/topics/stats.html

In any of the data were available, I would expect them at the URL above.

Exists: no
Digitized: no
Public: no
Without cost: no
Online: no
Machine-readable: no
Available in bulk: no
No license restrictions: yes
Up-to-date: no
In the state repository: no
Verifiable: no
Complete: no

**Comment by waldoj** [comment]
[I've got this up on the census now](https://census.usopendata.org/datasets.html?state=Minnesota)—thank you!
