### ISSUE TITLE
Missing Data: Minnesota Population

### ISSUE THREAD

**Issue by gboone** [opendata/Open-Data-Census#58]
STATE: MN
DATASET: Population
URL: https://mn.gov/admin/demography/data-by-topic/population-data/our-projections/index.jsp

Forecasts of municipal-level changes in population over coming years.

Exists: yes but see comments
Digitized: yes
Public: yes
Without cost: yes
Online: yes
Machine-readable: yes
Available in bulk: yes
No license restrictions: yes
Up-to-date: yes
In the state repository: no
Verifiable: yes
Complete: no

Comments:
Municipal level data does not exist, the state publishes [a CSV](https://mn.gov/admin/images/MN_County_Projections_Totals_2015-2045f.csv) of county projection totals and [an XLS](https://mn.gov/admin/images/MN_CountyEDR_Projections_AllData_2015-2045f.xlsx) of county projections for age and gender for every 5 years through 2045.

**Comment by waldoj** [comment]
[I've got this up on the census now](https://census.usopendata.org/datasets.html?state=Minnesota)—thank you!
