### ISSUE TITLE
Missing Data: Minnesota Vehicle Crashes

### ISSUE THREAD

**Issue by gboone** [opendata/Open-Data-Census#59]
STATE: MN
DATASET: Vehicle Crashes
URL: http://www.dot.state.mn.us/trafficeng/safety/crashdata.html

Incident-level reportable motor vehicle crash records.

Exists: yes
Digitized: yes
Public: yes
Without cost: yes
Online: yes
Machine-readable: no
Available in bulk: no
No license restrictions: yes
Up-to-date: yes
In the state repository: no
Verifiable: yes
Complete: yes

Comments:
These are PDFs of statistics, not data. It looks like you might be able to email someone and ask for the full data set. There's also this [map tool](mndotgis2.dot.state.mn.us/MnCMAT/MnCMAT.html) which is a flash app, requires authentication and is not available over HTTPS. There is also a "Crash Facts" report published annually as a PDF available here: https://dps.mn.gov/divisions/ots/reports-statistics/Pages/crash-facts.aspx

**Comment by waldoj** [comment]
[I've got this up on the census now](https://census.usopendata.org/datasets.html?state=Minnesota)—thank you!
