### ISSUE TITLE
Missing Data: WA checkbook

### ISSUE THREAD

**Issue by will-saunders** [opendata/Open-Data-Census#61]
STATE: WA
DATASET: Checkbook
URL: https://data.wa.gov/Procurements-and-Contracts/State-Vendor-Payments/sufm-u7rz

DESCRIPTION/COMMENTS:

This is a duplicate of state spending data extracted from fiscal.wa.gov - the state's budget and fiscal data portal, run by the legislature. Known shortcomings include: 
- all credit card data is reported as "US Bank"
- data is updated annually rather than in real time

**Comment by waldoj** [comment]
Change made! That brought the score up from an A- to an A. :) Thanks so much for putting that data on the repository and opening an issue here, @will-saunders!
