### ISSUE TITLE
Missing Data: WA Legislation

### ISSUE THREAD

**Issue by will-saunders** [opendata/Open-Data-Census#62]
STATE: WA
DATASET: Legislation
URL: https://data.wa.gov/dataset/Legislative-Web-Services-SOAP-API-/2v6q-xjj9

DESCRIPTION/COMMENTS:
Legislature'e SOAP/HTTP API has been added to the state repository at data.wa.gov

**Comment by waldoj** [comment]
:+1: The census has been updated accordingly. (And a grade of B is now an A-. :) Thanks, @will-saunders!
