### ISSUE TITLE
Missing Data: WA Real Estate

### ISSUE THREAD

**Issue by will-saunders** [opendata/Open-Data-Census#63]
STATE: WA
DATASET: Real Estate 
URL: https://data.wa.gov/dataset/Facilities-Inventory-System/shwa-savc 

DESCRIPTION/COMMENTS:

Facilities inventory has been listed in the state repository.
Known shortcomings: 
- it's a downloadable excel file rather than a native table (at publishing agency's request)
- does not show the acreage, parcel shape etc.

Please see also State Public Lands Inventory map:  http://publiclandsinventory.wa.gov/#Map

**Comment by waldoj** [comment]
Thank you for this, @will-saunders—the site has been updated to reflect these changes!
