### ISSUE TITLE
Missing Data: Texas Incarceration data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#68]
STATE: Texas
DATASET: Incarceration
URL: http://www.tdcj.texas.gov/tab1_public.html

The Texas Department of Criminal Justice releases a spreadsheet of all inmates in the state here under the label 'High Value Data Sets': http://www.tdcj.texas.gov/tab1_public.html

Direct URL: http://www.tdcj.texas.gov/documents/High_Value_Data_Sets.xlsx

**Comment by waldoj** [comment]
Whoa, no wonder I couldn't find any evidence that Texas had that data! What a weirdly bad filename and description. This data is really fascinating. I've seen nothing like this detail in any other state. Thanks so much for providing this—I'll update the census immediately to reflect it.
