### ISSUE TITLE
Missing Data: Puerto Rico Companies

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#69]
STATE: PR
DATASET: Companies
URL: https://data.pr.gov/en/Negocios-y-Corporaciones-/Extract-Data-Con-Censo-P-blico-y-Estatus-Activo/i6jc-4sg3

DESCRIPTION/COMMENTS:

The Puerto Rican Department of State releases a dataset of all active companies. Inactive ones are not included.

**Comment by waldoj** [comment]
Thank you! Nobody involved with this project is sufficiently fluent in Spanish to be able to find Puerto Rican data with any real confidence. I was the one who tried to track down this dataset, and now I see that I was using all the wrong words. :) [That record has been updated](https://census.usopendata.org/datasets.html?state=Puerto+Rico&datatype=Companies) to reflect your kind contribution. Thank you!
