### ISSUE TITLE
Missing Data: Florida Checkbook

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#70]
STATE: FL
DATASET: Checkbook
URL: http://www.myfloridacfo.com/transparency/vendorpayments.aspx

Florida checkbook data is in fact available for bulk download here: http://www.myfloridacfo.com/transparency/vendorpayments.aspx

**Comment by waldoj** [comment]
This is a big improvement—thank you! The census has been updated to reflect this.
