### ISSUE TITLE
Missing Data: Puerto Rico checkbook

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#72]
STATE: PR
DATASET: Chekbook
URL: http://www2.pr.gov/presupuestos/Pages/PRESUPUESTOSANTERIORES.aspx

Puerto Rico provides agency-level budgetary data ("Presupuesto por Agencia") in the aggregate. It is not granular to the level of specific outlays of what was actually spent, only what is budgeted by agency. Here's an example: http://www2.pr.gov/presupuestos/PresupuestoAprobado2015-2016/Pages/PRESUPUESTO-POR-AGENCIA.aspx

**Comment by waldoj** [comment]
That's close, but a step removed from what we're trying to measure. :) Budgets and spending are often quite different, unfortunately. But your Spanish-language data searching is clearly better than mine, because I didn't even find the budget!
