### ISSUE TITLE
Missing Data: Puerto Rico Legislation

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#73]
STATE: PR
DATASET: Legislation
URL: https://data.pr.gov/en/Abierto/Record-de-Votaci-n-de-Senado/fu3e-fj3e

There is some bulk data on Puerto Rico Senate legislation, but it's not complete by any means.

You already have the legislative search site for PR Senate. The legislative search for the lower house ("Asamblea") is here: http://www.tucamarapr.org/dnncamara/web/actividadlegislativa/tramitelegislativo.aspx

**Comment by waldoj** [comment]
Thanks, @SERutherford! I've updated [that record](https://census.usopendata.org/datasets.html?state=Puerto+Rico&datatype=Legislation) to include a link to the bulk PR senate data, too.

And thank you for your all of your helpful improvements to this project!
