### ISSUE TITLE
Missing Data: Texas Companies

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#75]
STATE: TX 
DATASET: Companies
URL: https://mycpa.cpa.state.tx.us/coa/Index.html

While direct searches on the Texas Secretary of State cost money per search, there is a free workaround. The state's tax authority, the Texas Comptroller of Public Accounts, has a search feature of taxable entity all companies -- incorporated in Texas or elsewhere -- that have the right to transact business in Texas. Much of the data is extracted directly from the Texas Secretary of State, such as registered agents and company officers.

Texas has started to post some of this data on its open data portal -- http://www.texastransparency.org/Data_Center/Search_Datasets.php -- under "Franchise TaxPayers" posted weekly. It's still far from a complete master list.

**Comment by waldoj** [comment]
This presents an interesting question/opportunity. This is useful information that is going to be valuable to many people looking at Texas's corporate grade on the census, but it's outside of the context of the census. So how to marry the two?

This makes me think that we should implement [Disqus](https://disqus.com/) on the site, to allow people to share information like this. If valuable information from people doesn't have a formal place in the census, we'll just create a new space for it! :)
