### ISSUE TITLE
Missing Data: Missouri Incarceration data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#80]
STATE: Missouri
DATASET: Offender Data File
URL: http://doc.mo.gov/Sunshine_Law/index.php

Missouri Department of Corrections posts a file weekly of all offenders that either are or have been under the supervision of the Department of Corrections.

http://doc.mo.gov/Sunshine_Law/index.php

**Comment by waldoj** [comment]
Hey, that's great—good for them for providing that level of detail. I've modified that record to point to the raw data, instead of their aggregated, PDF-bound data. Thank you!

**Comment by SERutherford** [comment]
Looks like the rating remained the same, though: https://census.usopendata.org/datasets.html?state=Missouri&datatype=Incarceration

**Comment by waldoj** [comment]
I have no idea what happened there. :-/ But I fixed it again! I hope it takes. :)

**Comment by SERutherford** [comment]
Looks like "available in bulk" is still set to 'no' and there are typos in some of the other fields. Is that correct?

Amazing project, by the way!

**Comment by waldoj** [comment]
What a strange problem! I've corrected those, but I'm not sure how it happened. This makes me all the more eager to move the data off of Google Sheets and into a CSV file, to facilitate validation. :-/ Thanks for your persistence. :)
