### ISSUE TITLE
Missing Data: Missouri Checkbook

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#81]
STATE: Missouri Checkbook
DATASET: State expenditures by agency
URL: https://data.mo.gov/Government-Administration/2014-State-Expenditures-As-Of-COB-Sept-30-2014/x5jr-mgwz

Annual Missouri state expenditures by agency are downloadable in bulk here: https://data.mo.gov/browse?limitTo=datasets&q=expenditures&sortBy=relevance&utf8=%E2%9C%93

**Comment by waldoj** [comment]
So Missouri provides this data in two different places, in different formats, maintained by (apparently) different groups. :-/ The source you found is definitely better than the one that we'd had listed before, bringing them up [from a B to a solid A](https://census.usopendata.org/datasets.html?state=Missouri). Thanks, @SERutherford!
