### ISSUE TITLE
Missing Data: Arizona Checkbook

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#83]
STATE: AZ
DATASET: Checkbook
URL: http://archivegao.az.gov/transparency/download.asp

Arizona expense data is in fact downloadable in bulk here: http://archivegao.az.gov/transparency/download.asp

**Comment by waldoj** [comment]
Great find! [This brought them up to a solid B](https://census.usopendata.org/datasets.html?state=Arizona). :) Thank you!
