### ISSUE TITLE
Missing Data: Tennessee Checkbook

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#84]
STATE: TN
DATASET: Checkbook
URL: http://www.tn.gov/transparenttn/section/state-financial-overview

Downloadable CSV files are available at the bottom of the page that provide all vendor payments by year for all state agencies. 2012, 2013, and 2014 are the only years available for download.

http://www.tn.gov/transparenttn/section/state-financial-overview

**Comment by waldoj** [comment]
Wonderful, thank you. All I could find before was a site that was unresponsive—presumably an abandoned site, replaced by this new one. They now get a grade of B-.
