### ISSUE TITLE
Missing Data: Missouri incarceration

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#89]
STATE: Missouri
DATASET: Offender Data File
URL: http://doc.mo.gov/Sunshine_Law/index.php

Looks like this one might still need to be updated. Missouri Department of Corrections posts a file weekly of all offenders that either are or have been under the supervision of the Department of Corrections.

http://doc.mo.gov/Sunshine_Law/index.php

**Comment by waldoj** [comment]
Closed by #80.
