### ISSUE TITLE
Missing Data: Nebraska Incarceration

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#90]
STATE: NE
DATASET: Incarceration
URL: http://dcs-inmatesearch.ne.gov/Corrections/COR_download.htm

Looks like Nebraska inmate data, filterable by facility, is downloadable in bulk as an Excel here: http://dcs-inmatesearch.ne.gov/Corrections/COR_download.htm

**Comment by waldoj** [comment]
That's a big improvement over that we had for Nebraska incarceration data. It's not quite on point for per-prison population data, but it's possible to infer per-prison population data from this. Thanks so much!
