### ISSUE TITLE
Missing Data: Kentucky Companies

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#91]
STATE: KY
DATASET: Companies
URL: http://www.sos.ky.gov/bus/Pages/Bulk-Data-Service.aspx

Bulk company data is available for download as Excel files, but only for a fee.

**Comment by waldoj** [comment]
This is an interesting arrangement—data is $2,000/month for commercial purposes, but free otherwise. Free data is a big improvement from _no_ data, which is all our survey had found. Thanks for a great find!
