### ISSUE TITLE
Missing Data: South Carolina Companies

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#92]
STATE: SC
DATASET: Companies
URL: http://scinteractive.sc.gov/Pages/SubscriberServices.aspx

"The South Carolina Secretary of State's Office charges an annual fee of $12,000 for access to monthly CSV files of all public information associated with Corporation filings."

**Comment by waldoj** [comment]
Great! You're mighty good at tracking these things down, @SERutherford. Thank you!
