### ISSUE TITLE
Missing Data: Florida Companies bulk data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#93]
STATE: FL
DATASET: Companies
URL: http://sunbiz.org/cor_downld.html

Here's the bulk company for free: http://sunbiz.org/cor_downld.html

Also available on a quarterly basis: ftp://ftp.dos.state.fl.us/public/doc/Quarterly/

**Comment by waldoj** [comment]
This is a huge improvement. Thank you!
