### ISSUE TITLE
Missing Data: Texas Companies bulk data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#94]
STATE: TX
DATASET: Companies
URL: https://direct.sos.state.tx.us/help/help-corp.asp?pg=bulk

Bulk company data is available for download as a CSV for a hefty fee: https://direct.sos.state.tx.us/help/help-corp.asp?pg=bulk

**Comment by waldoj** [comment]
Great to know that they offer bulk data—I've updated their record. Thank you!
