### ISSUE TITLE
Missing Data: Florida Incarceration per-facility inmate population data

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#95]
STATE: FL
DATASET: Incarceration
URL: http://www.dc.state.fl.us/pub/pop/facility/index.html

Per-facility inmate population records are available here: http://www.dc.state.fl.us/pub/pop/facility/index.html

**Comment by waldoj** [comment]
I knew that had to exist somewhere. You've got a talent for tracking these down, @SERutherford. :) Thanks!
