### ISSUE TITLE
Missing Data:

### ISSUE THREAD

**Issue by katerabinowitz** [opendata/Open-Data-Census#99]
STATE: DC 
DATASET: Vehicle Crash Data, 2010
URL: https://drive.google.com/folderview?id=0B3bjEjYnux8nQXAyNXBLZ3lFbm8&usp=drive_web

DESCRIPTION/COMMENTS: DDOT made 2010 vehicle crash data available for DC as part of a Vision Zero hackathon. The data is free but currently only exists on a google drive, not DC's open data website, and is only available in shape files.

**Comment by waldoj** [comment]
While this is certainly interesting to know about, I don't think we can include this in the survey. Between being five years old, being a one-off, and being hosted by a third party, I don't think it would be accurate to use this data to record DC crash data as being a going interest. But I'm certainly open to arguments to the contrary! :)

**Comment by katerabinowitz** [comment]
I don't disagree. Originally it sounded like they'd be releasing more data, so the storage and time period has been disappointing :/

**Comment by waldoj** [comment]
Oh, that does sound disappointing. I only knew the end result that there was no data to be found—getting your hopes up and then DDOT not following through must have been frustrating. :(

**Comment by katerabinowitz** [comment]
Ah! it's now on DC's open data website and looks to span 2010-2015 (despite writing 2010-2014 in the summary):
http://opendata.dc.gov/datasets/95254fae17bc4792bd47b53f71c2e503_19

**Comment by waldoj** [comment]
Wooo! [Updated](https://census.usopendata.org/datasets.html?state=Washington+DC)! With that addition, you moved DC from a 58%—a grade of F—up to 67—a grade of D+. Thanks, @katerabinowitz. :)

cc: @mattbailey0

**Comment by katerabinowitz** [comment]
:tada: :star2: :tada:
